window.esdocSearchIndex = [
  [
    "parserror/src/caseparser.js~caseparser",
    "class/src/caseParser.js~CaseParser.html",
    "<span>CaseParser</span> <span class=\"search-result-import-path\">parserror/src/caseParser.js</span>",
    "class"
  ],
  [
    "parserror/src/errorcase.js~errorcase",
    "class/src/errorCase.js~ErrorCase.html",
    "<span>ErrorCase</span> <span class=\"search-result-import-path\">parserror/src/errorCase.js</span>",
    "class"
  ],
  [
    "parserror/src/formattederror.js~formattederror",
    "class/src/formattedError.js~FormattedError.html",
    "<span>FormattedError</span> <span class=\"search-result-import-path\">parserror/src/formattedError.js</span>",
    "class"
  ],
  [
    "parserror/src/parserror.js~parserror",
    "class/src/parserror.js~Parserror.html",
    "<span>Parserror</span> <span class=\"search-result-import-path\">parserror/src/parserror.js</span>",
    "class"
  ],
  [
    "parserror/src/scope.js~scope",
    "class/src/scope.js~Scope.html",
    "<span>Scope</span> <span class=\"search-result-import-path\">parserror/src/scope.js</span>",
    "class"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/caseparser.js",
    "file/src/caseParser.js.html",
    "src/caseParser.js",
    "file"
  ],
  [
    "src/caseparser.js~caseparser#constructor",
    "class/src/caseParser.js~CaseParser.html#instance-constructor-constructor",
    "src/caseParser.js~CaseParser#constructor",
    "method"
  ],
  [
    "src/caseparser.js~caseparser#is",
    "class/src/caseParser.js~CaseParser.html#instance-get-is",
    "src/caseParser.js~CaseParser#is",
    "member"
  ],
  [
    "src/caseparser.js~caseparser#name",
    "class/src/caseParser.js~CaseParser.html#instance-get-name",
    "src/caseParser.js~CaseParser#name",
    "member"
  ],
  [
    "src/caseparser.js~caseparser#parse",
    "class/src/caseParser.js~CaseParser.html#instance-method-parse",
    "src/caseParser.js~CaseParser#parse",
    "method"
  ],
  [
    "src/caseparser.js~caseparsertype",
    "typedef/index.html#static-typedef-CaseParserType",
    "src/caseParser.js~CaseParserType",
    "typedef"
  ],
  [
    "src/errorcase.js",
    "file/src/errorCase.js.html",
    "src/errorCase.js",
    "file"
  ],
  [
    "src/errorcase.js~errorcase#constructor",
    "class/src/errorCase.js~ErrorCase.html#instance-constructor-constructor",
    "src/errorCase.js~ErrorCase#constructor",
    "method"
  ],
  [
    "src/errorcase.js~errorcase#name",
    "class/src/errorCase.js~ErrorCase.html#instance-get-name",
    "src/errorCase.js~ErrorCase#name",
    "member"
  ],
  [
    "src/errorcase.js~errorcase#parse",
    "class/src/errorCase.js~ErrorCase.html#instance-method-parse",
    "src/errorCase.js~ErrorCase#parse",
    "method"
  ],
  [
    "src/errorcase.js~errorcasedefinition",
    "typedef/index.html#static-typedef-ErrorCaseDefinition",
    "src/errorCase.js~ErrorCaseDefinition",
    "typedef"
  ],
  [
    "src/errorcase.js~errorcaseoptions",
    "typedef/index.html#static-typedef-ErrorCaseOptions",
    "src/errorCase.js~ErrorCaseOptions",
    "typedef"
  ],
  [
    "src/formattederror.js",
    "file/src/formattedError.js.html",
    "src/formattedError.js",
    "file"
  ],
  [
    "src/formattederror.js~formattederror#constructor",
    "class/src/formattedError.js~FormattedError.html#instance-constructor-constructor",
    "src/formattedError.js~FormattedError#constructor",
    "method"
  ],
  [
    "src/formattederror.js~formattederror#context",
    "class/src/formattedError.js~FormattedError.html#instance-member-context",
    "src/formattedError.js~FormattedError#context",
    "member"
  ],
  [
    "src/formattederror.js~formattederror#params",
    "class/src/formattedError.js~FormattedError.html#instance-member-params",
    "src/formattedError.js~FormattedError#params",
    "member"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/lib.js",
    "file/src/lib.js.html",
    "src/lib.js",
    "file"
  ],
  [
    "src/parserror.js",
    "file/src/parserror.js.html",
    "src/parserror.js",
    "file"
  ],
  [
    "src/parserror.js~parserror#addcase",
    "class/src/parserror.js~Parserror.html#instance-method-addCase",
    "src/parserror.js~Parserror#addCase",
    "method"
  ],
  [
    "src/parserror.js~parserror#addcases",
    "class/src/parserror.js~Parserror.html#instance-method-addCases",
    "src/parserror.js~Parserror#addCases",
    "method"
  ],
  [
    "src/parserror.js~parserror#addparser",
    "class/src/parserror.js~Parserror.html#instance-method-addParser",
    "src/parserror.js~Parserror#addParser",
    "method"
  ],
  [
    "src/parserror.js~parserror#addscope",
    "class/src/parserror.js~Parserror.html#instance-method-addScope",
    "src/parserror.js~Parserror#addScope",
    "method"
  ],
  [
    "src/parserror.js~parserror#constructor",
    "class/src/parserror.js~Parserror.html#instance-constructor-constructor",
    "src/parserror.js~Parserror#constructor",
    "method"
  ],
  [
    "src/parserror.js~parserror#getscope",
    "class/src/parserror.js~Parserror.html#instance-method-getScope",
    "src/parserror.js~Parserror#getScope",
    "method"
  ],
  [
    "src/parserror.js~parserror#globalscopename",
    "class/src/parserror.js~Parserror.html#instance-get-globalScopeName",
    "src/parserror.js~Parserror#globalScopeName",
    "member"
  ],
  [
    "src/parserror.js~parserror#parse",
    "class/src/parserror.js~Parserror.html#instance-method-parse",
    "src/parserror.js~Parserror#parse",
    "method"
  ],
  [
    "src/parserror.js~parserror#removescope",
    "class/src/parserror.js~Parserror.html#instance-method-removeScope",
    "src/parserror.js~Parserror#removeScope",
    "method"
  ],
  [
    "src/parserror.js~parserror#wrap",
    "class/src/parserror.js~Parserror.html#instance-method-wrap",
    "src/parserror.js~Parserror#wrap",
    "method"
  ],
  [
    "src/parserror.js~parserror#wrapforscopes",
    "class/src/parserror.js~Parserror.html#instance-method-wrapForScopes",
    "src/parserror.js~Parserror#wrapForScopes",
    "method"
  ],
  [
    "src/parserror.js~parserror.new",
    "class/src/parserror.js~Parserror.html#static-method-new",
    "src/parserror.js~Parserror.new",
    "method"
  ],
  [
    "src/parserror.js~parserroroptions",
    "typedef/index.html#static-typedef-ParserrorOptions",
    "src/parserror.js~ParserrorOptions",
    "typedef"
  ],
  [
    "src/parserror.js~parserrorparseoptions",
    "typedef/index.html#static-typedef-ParserrorParseOptions",
    "src/parserror.js~ParserrorParseOptions",
    "typedef"
  ],
  [
    "src/parserror.js~parserrorwrapper",
    "typedef/index.html#static-typedef-ParserrorWrapper",
    "src/parserror.js~ParserrorWrapper",
    "typedef"
  ],
  [
    "src/scope.js",
    "file/src/scope.js.html",
    "src/scope.js",
    "file"
  ],
  [
    "src/scope.js~scope#addcase",
    "class/src/scope.js~Scope.html#instance-method-addCase",
    "src/scope.js~Scope#addCase",
    "method"
  ],
  [
    "src/scope.js~scope#addparser",
    "class/src/scope.js~Scope.html#instance-method-addParser",
    "src/scope.js~Scope#addParser",
    "method"
  ],
  [
    "src/scope.js~scope#constructor",
    "class/src/scope.js~Scope.html#instance-constructor-constructor",
    "src/scope.js~Scope#constructor",
    "method"
  ],
  [
    "src/scope.js~scope#getcase",
    "class/src/scope.js~Scope.html#instance-method-getCase",
    "src/scope.js~Scope#getCase",
    "method"
  ],
  [
    "src/scope.js~scope#getparser",
    "class/src/scope.js~Scope.html#instance-method-getParser",
    "src/scope.js~Scope#getParser",
    "method"
  ],
  [
    "src/scope.js~scope#hascase",
    "class/src/scope.js~Scope.html#instance-method-hasCase",
    "src/scope.js~Scope#hasCase",
    "method"
  ],
  [
    "src/scope.js~scope#hasparser",
    "class/src/scope.js~Scope.html#instance-method-hasParser",
    "src/scope.js~Scope#hasParser",
    "method"
  ],
  [
    "src/scope.js~scope#name",
    "class/src/scope.js~Scope.html#instance-get-name",
    "src/scope.js~Scope#name",
    "member"
  ],
  [
    "src/scope.js~scope#removecase",
    "class/src/scope.js~Scope.html#instance-method-removeCase",
    "src/scope.js~Scope#removeCase",
    "method"
  ],
  [
    "src/scope.js~scope#removeparser",
    "class/src/scope.js~Scope.html#instance-method-removeParser",
    "src/scope.js~Scope#removeParser",
    "method"
  ],
  [
    "src/typedef.js",
    "file/src/typedef.js.html",
    "src/typedef.js",
    "file"
  ],
  [
    "src/typedef.js~class",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes",
    "src/typedef.js~Class",
    "external"
  ]
]